// <auto-generated />
using System;
using AMLService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMLService.Migrations
{
    [DbContext(typeof(AmlDbContext))]
    [Migration("20250928151458_DateTimeMigration")]
    partial class DateTimeMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMLService.Analysis", b =>
                {
                    b.Property<int>("AnalysisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnalysisID"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnalysisID");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("AMLService.Models.GeneratedDrug", b =>
                {
                    b.Property<int>("GeneratedDrugID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeneratedDrugID"));

                    b.Property<int>("AnalysisID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("ProteinStructure")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("GeneratedDrugID");

                    b.HasIndex("AnalysisID")
                        .IsUnique();

                    b.ToTable("GeneratedDrugs");
                });

            modelBuilder.Entity("AMLService.Models.GeneratedDrug", b =>
                {
                    b.HasOne("AMLService.Analysis", "Analysis")
                        .WithOne("GeneratedDrug")
                        .HasForeignKey("AMLService.Models.GeneratedDrug", "AnalysisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("AMLService.Analysis", b =>
                {
                    b.Navigation("GeneratedDrug")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
